include:
  - compose.caddy.yml
services:
  portainer:
    image: portainer/agent:2.36.0-alpine
    ports:
      - 9001:9001
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: unless-stopped
