services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:2.10.0-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped
networks:
  caddy:
    name: caddy
    driver: bridge
volumes:
  caddy_data: {}
