version: "3.8"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:2.9.2-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped
  portainer:
    image: portainer/portainer-ce:2.31.1-alpine
    labels:
      caddy: ${DOMAIN}
      caddy.reverse_proxy: "{{upstreams 9000}}"
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer/data:/data
    restart: unless-stopped
networks:
  caddy:
    name: caddy
    driver: bridge
volumes:
  caddy_data: {}
