version: "3.8"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:2.9.2-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped
  portainer:
    image: portainer/agent:2.31.0-alpine
    ports:
      - 9001:9001
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: unless-stopped
networks:
  caddy:
    name: caddy
    driver: bridge
volumes:
  caddy_data: {}
